/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as GovernmentJobsRouteImport } from './routes/government-jobs'
import { Route as FreelanceJobsRouteImport } from './routes/freelance-jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'

const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentJobsRoute = GovernmentJobsRouteImport.update({
  id: '/government-jobs',
  path: '/government-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceJobsRoute = FreelanceJobsRouteImport.update({
  id: '/freelance-jobs',
  path: '/freelance-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/freelance-jobs': typeof FreelanceJobsRoute
  '/government-jobs': typeof GovernmentJobsRoute
  '/internships': typeof InternshipsRoute
  '/jobs': typeof JobsRouteWithChildren
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/freelance-jobs': typeof FreelanceJobsRoute
  '/government-jobs': typeof GovernmentJobsRoute
  '/internships': typeof InternshipsRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/freelance-jobs': typeof FreelanceJobsRoute
  '/government-jobs': typeof GovernmentJobsRoute
  '/internships': typeof InternshipsRoute
  '/jobs': typeof JobsRouteWithChildren
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/contact'
    | '/dashboard'
    | '/freelance-jobs'
    | '/government-jobs'
    | '/internships'
    | '/jobs'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/companies/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/freelance-jobs'
    | '/government-jobs'
    | '/internships'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/companies'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/contact'
    | '/dashboard'
    | '/freelance-jobs'
    | '/government-jobs'
    | '/internships'
    | '/jobs'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/companies/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FreelanceJobsRoute: typeof FreelanceJobsRoute
  GovernmentJobsRoute: typeof GovernmentJobsRoute
  InternshipsRoute: typeof InternshipsRoute
  JobsRoute: typeof JobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-jobs': {
      id: '/government-jobs'
      path: '/government-jobs'
      fullPath: '/government-jobs'
      preLoaderRoute: typeof GovernmentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance-jobs': {
      id: '/freelance-jobs'
      path: '/freelance-jobs'
      fullPath: '/freelance-jobs'
      preLoaderRoute: typeof FreelanceJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesSlugRoute: CompaniesSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FreelanceJobsRoute: FreelanceJobsRoute,
  GovernmentJobsRoute: GovernmentJobsRoute,
  InternshipsRoute: InternshipsRoute,
  JobsRoute: JobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
